export const industryArr = [
  "Agriculture",
  "Automotive",
  "Banking",
  "Construction",
  "Education",
  "Energy",
  "Entertainment",
  "Finance",
  "Food",
  "Healthcare",
  "Hospitality",
  "Information Technology",
  "Insurance",
  "Manufacturing",
  "Marketing",
  "Media",
  "Mining",
  "Non-Profit",
  "Real Estate",
  "Retail",
  "Software",
  "Telecommunications",
  "Transportation",
  "Travel",
];

export const companySizeArr = [
  "1-10 employees",
  "11-50 employees",
  "51-200 employees",
  "201-500 employees",
  "501-1000 employees",
  "1001-5000 employees",
  "5001-10000 employees",
  "10001+ employees",
];

export const companyTypeArr = [
  "Sole Proprietorship",
  "Partnership",
  "Corporation",
  "Limited Liability Company",
  "Limited Liability Partnership",
  "Limited Partnership",
  "Limited Liability Corporation",
  "public limited company",
  "sole trader",
  "subsidiary",
  "trust",
];

export const skillOptions = [
  // AWS-related skills
  "AWS EC2",
  "AWS Lambda",
  "AWS S3",
  "AWS CloudFormation",
  "AWS RDS",
  "AWS DynamoDB",
  "AWS CloudFront",
  "AWS Route 53",
  "AWS IAM",
  "AWS Elastic Beanstalk",

  // AI-related skills
  "Machine Learning",
  "Deep Learning",
  "Natural Language Processing (NLP)",
  "Computer Vision",
  "TensorFlow",
  "PyTorch",
  "Reinforcement Learning",
  "Artificial Intelligence",
  "Data Science",
  "Neural Networks",

  // Cybersecurity-related skills
  "Penetration Testing",
  "Network Security",
  "Ethical Hacking",
  "Incident Response",
  "Cryptography",
  "Vulnerability Assessment",
  "Security Information and Event Management (SIEM)",
  "Firewall Management",
  "Security Auditing",
  "Cyber Threat Intelligence",

  // Web development skills
  "React",
  "Angular",
  "Vue.js",
  "Node.js",
  "Express.js",
  "Next.js",
  "GraphQL",
  "TypeScript",
  "RESTful API",
  "HTML & CSS",

  // Business-related skills
  "Project Management",
  "Agile Methodologies",
  "Business Strategy",
  "Digital Marketing",
  "Product Management",
  "Financial Analysis",
  "Market Research",
  "Leadership",
  "Business Development",
  "Salesforce",
];
